test_image: "test/data/out_000001.jpg"

root_window:
  name: "Main Window"

navigation_window:
  title: "Navigation Window"

annotation_window:
  title: "Annotation Window"

mouse_motion:
  windows: "<Motion>"
  linux: "<Motion>"

mouse_wheel:
  windows: "<MouseWheel>"
  linux:
    bind1: "<Button-4>"
    bind2: "<Button-5>"
  step_sensibility: 1.5

left_mouse_click:
  windows: "<Double-Button-1>"
  linux: "<Double-Button-1>"

SAM:
  device: "cpu"
  model: "vit_b" # vit_l; vit_b or vit_h

shortcuts:
  circle_mode: "b"
  drawed_contour_mode: "c"
  save_drawed_contour: " "
  selection_mode: "v"
  delete_contour: "BackSpace"
  apply_SAM: "s"
  annotation_mode: "<F9>"

#TODO: It should work with any image size, but its not working. We'll check this out in the future
image_viewer:
  width: 500
  height: 500
